### ISSUE TITLE
Unable to run the demo

### ISSUE THREAD

**Issue by aprofromindia** [petterh/react-native-android-activity#3]
I am unable to run the demo, by using both `react-native run-android` (from react-native-cli) and Android Studio run command, any idea how to run the demo.

Maybe kindly update the README with instruction on how to run the demo.

**Comment by petterh** [comment]
I've had problems with `react-native run-android` in the past. Please try the following; if it works for you I'll update the README:

* Connect your device
* Run **react-native start** to start the packager
* Run the app from Android Studio
* If this fails with the message "Could not get BatchedBridge, make sure your bundle is packaged correctly", your packager is likely not running.
* If it complains about connecting to the dev server, run **adb reverse tcp:8081 tcp:8081**

**Comment by petterh** [comment]
Closing for lack of response -- feel free to reopen if necessary.

**Comment by redexp** [comment]
@aprofromindia @petterh I resolve my problem of starting demo with changing `android/gradlew` file permissions to `0777`
