### ISSUE TITLE
 Activity class {com.demo.activity/com.demo.activity.MainActivity} does not exist.

### ISSUE THREAD

**Issue by Huai-Dc** [petterh/react-native-android-activity#4]
there has a error occur：

Starting the app on emulator-5554 (C:\Users\Administrator\AppData\Local\Android\sdk/platform-tools/adb -s emulator-5554 shell am start -n com.demo.activity/.MainActivity)...
Starting: Intent { cmp=com.demo.activity/.MainActivity }
Error type 3
Error: Activity class {com.demo.activity/com.demo.activity.MainActivity} does not exist.

**Comment by petterh** [comment]
Haven't seen that myself, but have a look at [this SO post](https://stackoverflow.com/questions/20915266/error-type-3-error-activity-class-does-not-exist). It has several suggestions.

**Comment by jjchula** [comment]
Have a look in app/build.gradle
1) applicationId "com.activity"  <--- com.demo.activity
2) Oh.. buildToolsVersion and defaultConfig are inside splits

**Comment by petterh** [comment]
I've tweaked `app/build.gradle`. Feel free to reopen if that doesn't fix the issue.

**Comment by pawarvijay** [comment]
i followed all below steps and it worked
https://github.com/react-community/react-native-maps/issues/2188#issuecomment-395977497
