### ISSUE TITLE
combine steps 1 & 3

### ISSUE THREAD

**Issue by ziarno** [petterh/react-native-android-activity#5]
Hi,

Great tutorial! I need a little help - I'd like to have a reactMethod, that accepts a callback which is then passed to the activity that I've started.
Something like this
```
    @ReactMethod
    void start(@Nonnull Callback callback) {
        ReactApplicationContext context = getReactApplicationContext();
        Intent intent = new Intent(context, CameraScannerActivity.class);
        context.startActivity(intent);
       // this part doesn't work:
        CameraScannerActivity activity = (CameraScannerActivity) getCurrentActivity();
        activity.setCallback(callback);
    }
```

Any idea how I can achieve that? Or how can the `CameraScannerActivity` pass some event data to the callback?

**Comment by petterh** [comment]
Interesting question -- I'll look into it when I have time.

**Comment by ziarno** [comment]
Cool, thanks a lot! I thought about using events, but seemed complicated ;)

**Comment by petterh** [comment]
The callbacks passed to `ReactMethod`s are no good as a permanent channel from Java to RN, they permit only a single call. So it's either use an event or call a JS method, both of which are now in the sample -- I don't see a huge difference between those mechanisms for this particular scenario.
