### ISSUE TITLE
Issue with complicated native app

### ISSUE THREAD

**Issue by anky21** [petterh/react-native-android-activity#6]
Hi Petter,

I tried your demo and tried your code with a simple native android app (react native demo). I was able to call a native activity from react native. However, when I tried to apply it to a more complicated native app, it started give me this error:
`Cannot read property 'dialNumber' of undefined`
I've tried really everything. I made the package.json file almost the same as yours. I changed the setttings in build.gradle as yours as well. 

I just tried another not-too-complicated app and it didn't work. 
https://github.com/anky21/Integrate-React-Native-in-Android

Is it possible that some libraries are interfering with React Native? Or the project has to be created through `react-native init`? What do you think the problem can be? 

Cheers

**Comment by petterh** [comment]
Your problem is that you don't add the `ActivityStarterReactPackage` to your `ReactInstanceManager`. In `ReactActivity.onCreate`, add this line:

    mReactInstanceManager = ReactInstanceManager.builder()
            .setApplication(getApplication())
            .setBundleAssetName("index.android.bundle")
            .setJSMainModuleName("index.android")
            .addPackage(new MainReactPackage())
            .addPackage(new ActivityStarterReactPackage()) // <== ADD THIS LINE
            .setUseDeveloperSupport(BuildConfig.DEBUG)
            .setInitialLifecycleState(mLifecycleState)
            .build();

Another problem occurs if you don't already have the overlay permission -- after starting the `Settings.ACTION_MANAGE_OVERLAY_PERMISSION`, you still go ahead and create the react native window. Better to refactor this into its own method, which you then call from `onCreate` if you _don't_ have to ask for overlay permissions, and from `onActivityResult` otherwise. (Provided you got the permission.)

(The overlay permission thing only applies to debug builds, but still.)

**Comment by anky21** [comment]
Thanks a lot. It solved the problem. Thank you so much. 
Brisbane is a lot hotter for sure. Come down to Gold Coast sometimes. It's quite nice.

**Comment by DenisLebedinsky** [comment]
I have a problem with adding ActivityStarterModule: 
`.addPackage(new` ActivityStarterModule())`

i not give reactContect, but i haven't this context in 
`mReactInstanceManager` = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setCurrentActivity(this)
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index")
                .addPackage(new MainReactPackage())
                .addPackage(new ActivityStarterModule())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
`

**Comment by petterh** [comment]
`ActivityStarterModule` is not a react package. Try `ActivityStarterReactPackage` instead.

**Comment by DenisLebedinsky** [comment]
Thank you for fast answer, but i found resolve in your stack's answer. =)
I create ActivityStarterReactPackage, and it resolved my problem.
